/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  // All colors are defined as static values — no dark: variant needed
  // The html element already has class="dark" for Material Symbols compatibility
  theme: {
    extend: {
      colors: {
        "on-error": "#1a0000",
        "error": "#ef4444",
        "surface-dim": "#0c0c0f",
        "on-error-container": "#fca5a5",
        "primary-container": "#7c3aed",
        "surface-container-lowest": "#09090b",
        "surface-container-low": "#0f0f12",
        "secondary": "#71717a",
        "primary-fixed": "#ede9fe",
        "background": "#09090b",
        "surface-tint": "#a78bfa",
        "primary-fixed-dim": "#c4b5fd",
        "tertiary": "#34d399",
        "surface-container": "#121215",
        "on-primary-container": "#ede9fe",
        "on-tertiary": "#001a12",
        "on-surface-variant": "#a1a1aa",
        "on-primary-fixed": "#2e1065",
        "primary": "#a78bfa",
        "surface": "#0c0c0f",
        "on-primary": "#0a0012",
        "outline-variant": "#27272a",
        "tertiary-container": "#065f46",
        "on-tertiary-container": "#bbf7d0",
        "surface-bright": "#18181b",
        "outline": "#52525b",
        "on-secondary": "#09090b",
        "surface-container-highest": "#1e1e22",
        "inverse-primary": "#5b21b6",
        "on-secondary-container": "#a1a1aa",
        "secondary-fixed": "#a1a1aa",
        "inverse-surface": "#fafafa",
        "on-surface": "#fafafa",
        "secondary-container": "#27272a",
        "error-container": "#3b1111",
        "on-background": "#fafafa",
        "surface-variant": "#18181b",
        "surface-container-high": "#18181b",
        "secondary-fixed-dim": "#71717a",
        "inverse-on-surface": "#09090b",
        "on-error-var": "#fca5a5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        body: ["Geist", "sans-serif"],
        label: ["Geist", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.2s ease-out",
        "slide-in": "slideIn 0.3s cubic-bezier(0.16,1,0.3,1)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideIn: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
}
